name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore tools
        run: dotnet tool restore
        working-directory: ./Src
      - name: Build templates
        # TargetFramework specified so this only runs once rather than per framework
        run: dotnet msbuild -t:TextTemplateTransform -p:TargetFramework=NA Src
      - name: Debug Build
        run: dotnet build --configuration=Debug -p:TreatWarningsAsErrors=true Src
      - name: Release Build
        run: dotnet build --configuration=Release -p:TreatWarningsAsErrors=true Src
      - name: CPU Tests
        run: dotnet test --configuration=Release ./Src/ILGPU.Tests.CPU
      - name: Upload bin directory
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-bin
          path: Bin

  nuget-package:
    runs-on: windows-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Windows binaries
        uses: actions/download-artifact@v2
        with:
          name: Windows-bin
          path: Bin
      - name: Set up NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'
      - name: Create NuGet package
        run: nuget pack .nuget/ILGPU.nuspec
      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: ILGPU.*.nupkg
